- name: WandbCallback
  configs:
    project: automatic-medical-coding
    entity: null
    dir: /home/mixlab/tabular/icd-coding/experiments
- name: SaveBestModelCallback
  configs:
    split: val
    target: all
    metric: map
- name: EarlyStoppingCallback
  configs:
    split: val
    target: all
    metric: map
    patience: 6
